[package]
name = "alfred-pods"
version = "1.0.1"
authors = ["Fernando Paredes <nano@fdp.io>"]

[dependencies]
quicli = "0.3.0"
alfred = "4.0.1"
reqwest = "0.8.8"
serde = "1.0.79"
serde_json = "1.0.27"
serde_derive = "1.0.79"
