[package]
name = "alfred-pods"
version = "1.0.0"
authors = ["Fernando Paredes <nano@fdp.io>"]

[dependencies]
quicli = "0.2.0"
alfred = "4.0.1"
reqwest = "0.8.5"
serde = "1.0.27"
serde_json = "1.0.10"
serde_derive = "1.0.27"
